# Generated by Django 2.0.6 on 2019-03-01 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=40)),
                ('hours', models.IntegerField()),
                ('workDate', models.DateField(blank=True, default=datetime.datetime(2019, 3, 1, 15, 39, 31, 889524, tzinfo=utc), null=True)),
                ('entryDate', models.DateField(default=datetime.datetime(2019, 3, 1, 15, 39, 31, 889546, tzinfo=utc))),
            ],
        ),
    ]
