# Generated by Django 2.0.6 on 2019-03-01 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacherRecordApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecordmodel',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 15, 44, 57, 944822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classrecordmodel',
            name='workDate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 1, 15, 44, 57, 944799, tzinfo=utc), null=True),
        ),
    ]
