# Generated by Django 2.0.6 on 2019-03-01 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacherRecordApp', '0002_auto_20190301_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='classrecordmodel',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classrecordmodel',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='classrecordmodel',
            name='teacherName',
        ),
        migrations.AlterField(
            model_name='classrecordmodel',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 16, 48, 7, 715998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classrecordmodel',
            name='workDate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 1, 16, 48, 7, 715973, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='classrecordmodel',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='teacherRecordApp.TeacherRecordModel'),
        ),
    ]
