# Generated by Django 2.0.6 on 2019-03-01 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacherRecordApp', '0004_auto_20190301_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecordmodel',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 16, 52, 5, 207557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classrecordmodel',
            name='teacher',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='teacherRecordApp.TeacherRecordModel'),
        ),
        migrations.AlterField(
            model_name='classrecordmodel',
            name='workDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 16, 52, 5, 207534, tzinfo=utc)),
        ),
    ]
