# Generated by Django 2.0.6 on 2019-03-01 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacherRecordApp', '0008_auto_20190301_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrecordmodel',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classrecordmodel',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classrecordmodel',
            name='subject',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='classrecordmodel',
            name='teacherName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='classrecordmodel',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 16, 59, 1, 855117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classrecordmodel',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classrecordmodel',
            name='workDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 16, 59, 1, 855095, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='TeacherRecordModel',
        ),
    ]
